# Site settings
title: Public Safety Analytics Resource Compendium
description: "Links to and descriptions of analytics resources for public safety"
baseurl: "/Public_Safety_Analytics_Resources" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: Public_Safety_Analytics_Resources

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /Public_Safety_Analytics_Resources/

host: 0.0.0.0
